language: node_js
node_js:
  - "0.10"
notifications:
  email:
    recipients:
      - joebm08@gmail.com
services: mongodb
script: 
- "node express.js &"
- "sleep 5"
- "./node_modules/mocha/bin/mocha *.test.js"